### ISSUE TITLE
Bug caused by an unknown reason

### ISSUE THREAD

**Issue by tnhung2011** [JackMcKew/pyinstaller-action-linux#12]
I think I found a bug
![image](https://user-images.githubusercontent.com/89075831/158000991-d52801c7-16f5-450b-acc7-f3c5bf11636e.png)
Causes by the `*.spec` loader?
Maybe it relates to https://github.com/JackMcKew/pyinstaller-action-windows/issues/19?
Version compatibility? [build_main.py#l752](https://github.com/pyinstaller/pyinstaller/blob/15f23a8a89be5453b3520df8fc3e667346e103a6/PyInstaller/building/build_main.py#L752)?
I'm a starter programmer so I don't know what causes it...

**Comment by JackMcKew** [comment]
From my understanding, I'm not sure you can specify any spec file but rather have to specify a specific file, this should hopefully resolve the problem :) Let me know how you go

**Comment by JackMcKew** [comment]
Closing due to stale
