### ISSUE TITLE
Kivy support

### ISSUE THREAD

**Issue by GreenJon902** [JackMcKew/pyinstaller-action-linux#14]
I cannot get kivy to compile, it works fine for the windows version of this, but not for linux. I get 
`ERROR: Could not build wheels for Kivy, which is required to install pyproject.toml-based projects` which is probably caused by `GL/gl.h: No such file or directory`. Google seems to think I need to install `libgl1-mesa-dev` but I could not get it too install on my side. A flag like the tkinter one probably work if you don't want it to install for everyone who may not need it, but kivy is also big enough to justify dedicating its own flag.

**Comment by JackMcKew** [comment]
Hey, all for it! Please feel free to open a PR :)

**Comment by GreenJon902** [comment]
@JackMcKew
Hey I'm trying to work on this but apt-get seems unable to access anything. Giving alot of errrors like `Err http://archive.ubuntu.com/ precise/main Sources
  404  Not Found [IP: 185.125.190.39 80]`, Do you have any clue why or how I could fix this?

**Comment by JackMcKew** [comment]
Hi @GreenJon902, the issue you're referencing is https://github.com/JackMcKew/pyinstaller-action-linux/issues/9

**Comment by JackMcKew** [comment]
Hi, could you please try using this branch and see if it solves this issue?

```
- name: Package Application
      uses: JackMcKew/pyinstaller-action-linux@python3.10
      with:
        path: src
```

**Comment by GreenJon902** [comment]
Thanks, that has helped. I have created a pull request with a kivy setting at #15.
