### ISSUE TITLE
pyinstaller with package as one file

### ISSUE THREAD

**Issue by rupesh3loq** [JackMcKew/pyinstaller-action-linux#4]
How to change this optional arguments and what to generate.
![image](https://user-images.githubusercontent.com/51986351/102912373-4f8e0e80-44a3-11eb-97e4-48690fbb9edd.png)

**Comment by JackMcKew** [comment]
All this is configurable for use with this action via spec files (and in my opinion is better practice)

Find the documentation over at: https://pyinstaller.readthedocs.io/en/stable/spec-files.html

**Comment by JackMcKew** [comment]
Closing due to no update
