### ISSUE TITLE
ModuleNotFoundError: No module named 'requests'

### ISSUE THREAD

**Issue by pranjal-joshi** [JackMcKew/pyinstaller-action-linux#6]
Hello,

This Github action successfully compiles the script and generates binary file but running the binary file throws following error:
`ModuleNotFoundError: No module named 'requests'`

Here is my `requirements.txt`:
```
...
requests # Installed as dependency for yfinance, cachecontrol
...
```

Here is my `.spec` file: [https://github.com/pranjal-joshi/Screeni-py/blob/pre-main/src/screenipy.spec](https://github.com/pranjal-joshi/Screeni-py/blob/pre-main/src/screenipy.spec)

**Observation**: Also I've observed that size of compiled binaries is very small (approx 6MB). However, the size of compiled binary on my local machine is around 31MB which is working fine without any error.

**Comment by JackMcKew** [comment]
`pyinstaller-action-linux` looks within the `src` directory for the `requirements.txt` file, while yours seems to be in the root, hope this helps :)

**Comment by JackMcKew** [comment]
I note that a PR was made for the requirements file path to be configurable for the windows equivalent: https://github.com/JackMcKew/pyinstaller-action-windows/pull/15 but I haven't got around to bringing it to this action

**Comment by pranjal-joshi** [comment]
> `pyinstaller-action-linux` looks within the `src` directory for the `requirements.txt` file, while yours seems to be in the root, hope this helps :)

Ok. This helps. But, I have a new problem.
I need to set up a dependency named [TA-lib](https://github.com/mrjbq7/ta-lib). For that, I need to run the following commands in the shell before executing pyinstaller.
```
$ tar -xzf ta-lib-0.4.0-src.tar.gz
$ cd ta-lib/
$ ./configure --prefix=/usr
$ make
$ sudo make install
```
So, How can I do it with your GitHub action?

**Comment by pranjal-joshi** [comment]
> > `pyinstaller-action-linux` looks within the `src` directory for the `requirements.txt` file, while yours seems to be in the root, hope this helps :)
> 
> Ok. This helps. But, I have a new problem.
> I need to set up a dependency named [TA-lib](https://github.com/mrjbq7/ta-lib). For that, I need to run the following commands in the shell before executing pyinstaller.
> ```
> $ tar -xzf ta-lib-0.4.0-src.tar.gz
> $ cd ta-lib/
> $ ./configure --prefix=/usr
> $ make
> $ sudo make install
> ```
> So, How can I do it with your GitHub action?

Hello, Thanks for the great action!
But I have shifted to my custom workflow as my dependency setup is a bit weird to setup with this action.

Though, it would be great if you add an argument through which we can run commands to setup dependencies for windows, ubuntu and mac.

You may close this issue. Thanks.
