### ISSUE TITLE
ModuleNotFoundError: No module named 'PyQt5.sip'

### ISSUE THREAD

**Issue by ftharyanto** [JackMcKew/pyinstaller-action-linux#8]
My code contains PyQt5, I've successfully build it but when I tried to launch the executable file through terminal, this error showed up:
`Traceback (most recent call last):
  File "main.py", line 1, in <module>
ModuleNotFoundError: No module named 'PyQt5.sip'
[8402] Failed to execute script main
`

**Here is an example to reproduce the bug**
1. Fork https://github.com/ftharyanto/excel-merger
2. Apply some changes on the main branch
3. Push and wait until the the Github Action finished
4. Download and run the artifact

**Comment by JackMcKew** [comment]
I believe this may be from the specified files in the `.spec` for the project?

**Comment by JackMcKew** [comment]
Closing due to stale
